name: Defang
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: Whether to deploy up or down
        required: true
        default: up
        type: choice
        options:
          - up
          - down
      stack:
        description: The stack to deploy up or down. (Leave blank for default)
        default: production
jobs:
  defang:
    name: Defang ${{ github.event.inputs.action || 'up' }} ${{ github.event.inputs.stack || 'production' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    concurrency:
      cancel-in-progress: false
      group: deploy-nextjs-${{ github.event.inputs.stack || 'production' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: projects/625809054533/locations/global/workloadIdentityPools/defang-github/providers/github-actions-yp3p58
      - name: Defang ${{ github.event.inputs.action || 'up' }} ${{ github.event.inputs.stack || 'production' }}
        uses: DefangLabs/defang-github-action@v1.4.0
        with:
          command: ${{ github.event.inputs.action || 'up' }}
          project: nextjs
          stack: ${{ github.event.inputs.stack || 'production' }}
      - name: Deployment Summary
        uses: DefangLabs/defang-github-action@v1.4.0
        with:
          command: services
          project: nextjs
          stack: ${{ github.event.inputs.stack || 'production' }}
    environment: production
